[tools]
bat = "latest"
chezmoi = "latest"
fzf = "latest"
lsd = "latest"
ripgrep = "latest"
neovim = "latest"
node = "latest"
python = "latest"
uv = "latest"
flux2 = "latest"
kubectl = "latest"
k9s = "latest"
